### ISSUE TITLE
PMTiles instead of MVT?

### ISSUE THREAD

**Issue by rmx90210** [workspublic/internet-xplorer#2]
Right now the map loads in [Mapbox vector tiles](https://docs.mapbox.com/data/tilesets/guides/vector-tiles-introduction/), which have some nice qualities (static files; pretty easy to generate with Tippecanoe) and also some not-nice qualities (wrangling thousands of nested directories in the cloud as well as locally can be a bear).

[PMTiles](https://protomaps.com/docs) are an intriguing, single-file alternative. They seem to work best with MapLibre GL, so this would an entail a migration away from Mapbox GL as well, but that _should_ be trivial given the backwards-compatibility.

**Comment by rbrtmrtn** [comment]
[MapTiler](https://www.maptiler.com/) seems to work with Maplibre and has [this](https://cloud.maptiler.com/maps/basic-v2-dark/) dark style (which can be customized).

Also it's [possible](https://github.com/maplibre/maplibre-gl-js/discussions/1226) to bring Mapbox styles into Maplibre (though it may impact pricing/free-tier limits).

**Comment by rmx90210** [comment]
Deployed with 5595876 🎉
